
ports ={
    "20": "FTP (File Transfer Protocol)",
    "21": "FTP (File Transfer Protocol)",
    "22": "SSH (Secure Shell)",
    "23": "Telnet",
    "25": "SMTP (Simple Mail Transfer Protocol)",
    "53": "DNS (Domain Name System)",
    "67": "DHCP (Dynamic Host Configuration Protocol)",
    "68": "DHCP (Dynamic Host Configuration Protocol)",
    "69": "TFTP (Trivial File Transfer Protocol)",
    "80": "HTTP (Hypertext Transfer Protocol)",
    "110": "POP3 (Post Office Protocol version 3)",
    "119": "NNTP (Network News Transfer Protocol)",
    "123": "NTP (Network Time Protocol)",
    "143": "IMAP (Internet Message Access Protocol)",
    "161": "SNMP (Simple Network Management Protocol)",
    "162": "SNMP (Simple Network Management Protocol)",
    "179": "BGP (Border Gateway Protocol)",
    "443": "HTTPS (HTTP Secure)",
    "445": "SMB (Server Message Block)",
    "465": "SMTPS (Secure SMTP)",
    "514": "Syslog",
    "587": "SMTP (with encryption)",
    "631": "IPP (Internet Printing Protocol)",
    "993": "IMAPS (Secure IMAP)",
    "995": "POP3S (Secure POP3)",
    "1080": "SOCKS Proxy",
    "1433": "Microsoft SQL Server",
    "1521": "Oracle Database",
    "1723": "PPTP (Point-to-Point Tunneling Protocol)",
    "1883": "MQTT (Message Queuing Telemetry Transport)",
    "2049": "NFS (Network File System)",
    "2375": "Docker (unencrypted)",
    "2376": "Docker (encrypted)",
    "3306": "MySQL/MariaDB",
    "3389": "RDP (Remote Desktop Protocol)",
    "5432": "PostgreSQL",
    "5900": "VNC (Virtual Network Computing)",
    "6379": "Redis",
    "8080": "HTTP Alternative",
    "8443": "HTTPS Alternative",
    "9092": "Apache Kafka"
}  